# GENERATED by `tugboat fleet gen` — do not edit.
# Sources: each service's deploy.toml [state] block + fleet.toml [backup].
# Adding a stateful service means declaring it there, not editing scripts.

# /var/lib/<entry> SQLite databases, snapshotted via the online-backup API.
SQLITE_DBS="clothes/clothes.db depot/depot.db lagoon/lagoon.sqlite mirror/mirror.db recipes/recipes.db regatta/regatta.db"

# /var/lib/<entry> directories whose plain files are backed up in place.
RAW_DIRS="breakwater ferry tugboat"
