#!/usr/bin/env bash
#
# Deploy Lighthouse to the VPS.
#
#   1. Build the React frontend locally (the VPS's Node is too old for Vite).
#   2. Rsync the Rust sources + built frontend to the VPS.
#   3. On the VPS: install the Rust toolchain if needed, build the release
#      binary, and install the binary, assets, config, service user, and unit.
#
# The dashboard binds to the VPS's Tailscale IP so it is reachable only from the
# tailnet. If Tailscale isn't logged in yet (`tailscale up`), the script still
# installs everything but leaves the service stopped and tells you what to run.
#
# Usage:  deploy/deploy.sh            (host defaults to the `deepwa7er` ssh alias)
#         LIGHTHOUSE_HOST=myalias deploy/deploy.sh
set -euo pipefail

HOST="${LIGHTHOUSE_HOST:-deepwa7er}"
REMOTE_BUILD="/opt/lighthouse/build"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo ">> Building frontend locally..."
(cd "$PROJECT_DIR/web" && bun install && bun run build)

echo ">> Syncing sources to $HOST:$REMOTE_BUILD ..."
ssh "$HOST" "mkdir -p '$REMOTE_BUILD'"
rsync -az --delete \
  "$PROJECT_DIR/Cargo.toml" \
  "$PROJECT_DIR/Cargo.lock" \
  "$PROJECT_DIR/lighthouse.toml" \
  "$HOST:$REMOTE_BUILD/"
rsync -az --delete "$PROJECT_DIR/src/" "$HOST:$REMOTE_BUILD/src/"
rsync -az --delete "$PROJECT_DIR/web/dist/" "$HOST:$REMOTE_BUILD/web-dist/"
rsync -az "$SCRIPT_DIR/lighthouse.service" "$HOST:$REMOTE_BUILD/lighthouse.service"
rsync -az "$SCRIPT_DIR/lighthouse.target" "$HOST:$REMOTE_BUILD/lighthouse.target"

echo ">> Building and installing on $HOST ..."
ssh "$HOST" 'bash -s' <<'REMOTE'
set -euo pipefail
BUILD=/opt/lighthouse/build

# --- Rust toolchain ---------------------------------------------------------
if ! command -v cargo >/dev/null 2>&1 && [ ! -f "$HOME/.cargo/env" ]; then
  echo ">> Installing rustup (minimal profile)..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --profile minimal --default-toolchain stable
fi
# shellcheck disable=SC1091
. "$HOME/.cargo/env"

# --- Build ------------------------------------------------------------------
echo ">> Building release binary..."
cd "$BUILD"
cargo build --release

# --- Install binary + assets ------------------------------------------------
install -Dm755 target/release/lighthouse /usr/local/bin/lighthouse
mkdir -p /opt/lighthouse/web
rm -rf /opt/lighthouse/web/*
cp -r web-dist/. /opt/lighthouse/web/

# --- Service user (least privilege: journal read only) ----------------------
if ! id lighthouse >/dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin lighthouse
fi

# --- Config -----------------------------------------------------------------
mkdir -p /etc/lighthouse
[ -f /etc/lighthouse/config.toml ] || install -m644 lighthouse.toml /etc/lighthouse/config.toml

# Auto-fill the bind address only while it is still the baseline placeholder —
# this covers both the first deploy and a re-deploy after `tailscale up`, and
# never clobbers a bind you have deliberately edited.
TSIP="$(tailscale ip -4 2>/dev/null | head -1 || true)"
if [ -n "$TSIP" ] && grep -q '^bind = "100.64.0.1"' /etc/lighthouse/config.toml; then
  sed -i "s|^bind = .*|bind = \"$TSIP\"|" /etc/lighthouse/config.toml
  echo ">> Bound dashboard to Tailscale IP $TSIP"
fi
chown -R lighthouse:lighthouse /etc/lighthouse /opt/lighthouse/web

# --- discovery target -------------------------------------------------------
# Passive grouping target whose members Lighthouse discovers. Install it before
# generating the polkit grant so its membership is queryable.
TARGET="$(grep -oP '^target = "\K[^"]+' /etc/lighthouse/config.toml || true)"
TARGET="${TARGET:-lighthouse.target}"
install -m644 lighthouse.target "/etc/systemd/system/$TARGET"
systemctl daemon-reload

# --- polkit grant -----------------------------------------------------------
# Let the unprivileged `lighthouse` user start/stop/restart EXACTLY the units it
# monitors, via systemd's D-Bus + polkit. This needs no sudo/setuid, so it works
# under the unit's NoNewPrivileges=true. The allowed-unit list is regenerated on
# every deploy from the target's members plus any units pinned in the config, so
# enrolling a service for CONTROL means re-running this script (viewing updates
# live, since discovery happens at request time).
DISCOVERED="$(systemctl show "$TARGET" --property=Wants --value --no-pager | tr ' ' '\n' | grep '\.service$' || true)"
PINNED="$(grep -oP '^\s*unit\s*=\s*"\K[^"]+' /etc/lighthouse/config.toml || true)"
UNIT_LIST="$(printf '%s\n%s\n' "$DISCOVERED" "$PINNED" | grep -v '^$' | sort -u)"
UNIT_ARRAY="$(printf '%s\n' "$UNIT_LIST" | grep -v '^$' | sed 's/^/        "/; s/$/",/')"
mkdir -p /etc/polkit-1/rules.d
cat > /etc/polkit-1/rules.d/50-lighthouse.rules <<RULE
// Generated by lighthouse deploy.sh — DO NOT EDIT BY HAND (regenerated on deploy).
// Allows the unprivileged 'lighthouse' service user to start/stop/restart only
// the units it monitors. No password/admin prompt (returns YES), so it works
// non-interactively from the service.
polkit.addRule(function (action, subject) {
    if (subject.user !== "lighthouse") {
        return polkit.Result.NOT_HANDLED;
    }
    if (action.id !== "org.freedesktop.systemd1.manage-units") {
        return polkit.Result.NOT_HANDLED;
    }
    var allowedVerbs = ["start", "stop", "restart"];
    var allowedUnits = [
$UNIT_ARRAY
    ];
    if (
        allowedVerbs.indexOf(action.lookup("verb")) !== -1 &&
        allowedUnits.indexOf(action.lookup("unit")) !== -1
    ) {
        return polkit.Result.YES;
    }
    return polkit.Result.NOT_HANDLED;
});
RULE
chmod 644 /etc/polkit-1/rules.d/50-lighthouse.rules
echo ">> Installed polkit rule for units: $(echo "$UNIT_LIST" | tr '\n' ' ')"

# --- docker socket-proxy ----------------------------------------------------
# Lighthouse talks to Docker only through this proxy (never the raw socket). It
# is a secure-by-default filter that allows EXACTLY four operations — container
# list/inspect/logs (GET) and start/stop/restart (POST) — and denies everything
# else (create, delete, exec, images, networks, volumes, the daemon, …). That
# keeps Docker control from becoming a root-equivalent grant, mirroring the
# tightly-scoped polkit rule on the systemd side. It is published on host
# loopback only, and runs unprivileged with just the host docker group added so
# it can read the socket.
# Created if absent; to change its settings, `docker rm -f` it and re-deploy.
if command -v docker >/dev/null 2>&1; then
  if ! docker ps -a --format '{{.Names}}' | grep -qx lighthouse-socket-proxy; then
    DOCKER_GID="$(getent group docker | cut -d: -f3)"
    docker run -d --name lighthouse-socket-proxy --restart unless-stopped \
      --group-add "$DOCKER_GID" \
      -p 127.0.0.1:2375:2375 \
      -v /var/run/docker.sock:/var/run/docker.sock:ro \
      wollomatic/socket-proxy:1 \
      -loglevel=info -listenip=0.0.0.0 -allowfrom=0.0.0.0/0 \
      -allowGET='(/v[0-9.]+)?/containers/(json|[^/]+/json|[^/]+/logs)' \
      -allowPOST='(/v[0-9.]+)?/containers/[^/]+/(start|stop|restart)'
    echo ">> Started lighthouse-socket-proxy on 127.0.0.1:2375"
  else
    echo ">> lighthouse-socket-proxy already present"
  fi
else
  echo ">> docker not installed; skipping socket-proxy (systemd-only dashboard)"
fi

# --- systemd unit -----------------------------------------------------------
install -m644 lighthouse.service /etc/systemd/system/lighthouse.service
systemctl daemon-reload

# Enable (on boot) + start only if Tailscale is up; otherwise binding to the
# 100.x IP would fail, so we leave the unit installed but inactive rather than
# enabling a service that would crash-loop after a reboot.
if [ -n "$TSIP" ]; then
  systemctl enable lighthouse.service >/dev/null 2>&1 || true
  systemctl restart lighthouse.service
  sleep 1
  systemctl --no-pager --lines=0 status lighthouse.service | head -4
  PORT="$(grep -oP '^port = \K[0-9]+' /etc/lighthouse/config.toml)"
  echo ">> Lighthouse is up at http://$TSIP:$PORT"
else
  echo "!! Tailscale is not logged in yet, so the dashboard was installed but not started."
  echo "!! Run:  sudo tailscale up"
  echo "!! Then re-run this deploy script (it will set the bind IP, enable, and start the service)."
fi
REMOTE

echo ">> Done."
