#!/usr/bin/env bash
#
# Provision lighthouse's infrastructure on the VPS:
#   - the `lighthouse` service user (least privilege)
#   - the config (installed only if absent; bind address auto-filled to the
#     Tailscale IP while still the baseline placeholder)
#   - the discovery target (lighthouse.target)
#   - the polkit grant that lets the service start/stop/restart EXACTLY the units
#     enrolled in lighthouse.target (regenerated from current membership)
#   - the systemd unit
#
# Run this for first-time setup, and whenever you enroll a new service in
# lighthouse.target and want lighthouse to be able to control it (the polkit
# grant only changes here). Routine code/asset deploys go through tugboat
# (deploy.toml at the repo root), not this script — so this does not build,
# install the binary/web assets, or restart the service.
#
# Host: set LIGHTHOUSE_HOST (defaults to the `deepwa7er` ssh alias).
set -euo pipefail

HOST="${LIGHTHOUSE_HOST:-deepwa7er}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # deploy/
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
REMOTE=/opt/lighthouse/provision

echo ">> Syncing unit/target/config to $HOST ..."
ssh "$HOST" "mkdir -p '$REMOTE'"
rsync -az "$PROJECT_DIR/lighthouse.toml" "$HOST:$REMOTE/lighthouse.toml"
rsync -az "$SCRIPT_DIR/lighthouse.service" "$HOST:$REMOTE/lighthouse.service"
rsync -az "$SCRIPT_DIR/lighthouse.target" "$HOST:$REMOTE/lighthouse.target"

echo ">> Provisioning on $HOST ..."
ssh "$HOST" 'bash -s' <<'REMOTE'
set -euo pipefail
P=/opt/lighthouse/provision

# --- Service user (least privilege: journal read only) ----------------------
if ! id lighthouse >/dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin lighthouse
fi

# --- Static asset dir (tugboat ships into it) + config ----------------------
mkdir -p /opt/lighthouse/web
mkdir -p /etc/lighthouse
[ -f /etc/lighthouse/config.toml ] || install -m644 "$P/lighthouse.toml" /etc/lighthouse/config.toml

# Auto-fill the bind address only while it is still the baseline placeholder.
TSIP="$(tailscale ip -4 2>/dev/null | head -1 || true)"
if [ -n "$TSIP" ] && grep -q '^bind = "100.64.0.1"' /etc/lighthouse/config.toml; then
  sed -i "s|^bind = .*|bind = \"$TSIP\"|" /etc/lighthouse/config.toml
  echo ">> Bound dashboard to Tailscale IP $TSIP"
fi
chown -R lighthouse:lighthouse /etc/lighthouse

# --- Discovery target -------------------------------------------------------
TARGET="$(grep -oP '^target = "\K[^"]+' /etc/lighthouse/config.toml || true)"
TARGET="${TARGET:-lighthouse.target}"
install -m644 "$P/lighthouse.target" "/etc/systemd/system/$TARGET"
systemctl daemon-reload

# --- polkit grant -----------------------------------------------------------
# Regenerated from the target's members plus any units pinned in the config.
DISCOVERED="$(systemctl show "$TARGET" --property=Wants --value --no-pager | tr ' ' '\n' | grep '\.service$' || true)"
PINNED="$(grep -oP '^\s*unit\s*=\s*"\K[^"]+' /etc/lighthouse/config.toml || true)"
UNIT_LIST="$(printf '%s\n%s\n' "$DISCOVERED" "$PINNED" | grep -v '^$' | sort -u)"
UNIT_ARRAY="$(printf '%s\n' "$UNIT_LIST" | grep -v '^$' | sed 's/^/        "/; s/$/",/')"
mkdir -p /etc/polkit-1/rules.d
cat > /etc/polkit-1/rules.d/50-lighthouse.rules <<RULE
// Generated by lighthouse provision.sh — DO NOT EDIT BY HAND (regenerated on provision).
// Allows the unprivileged 'lighthouse' service user to start/stop/restart only
// the units it monitors. No password/admin prompt (returns YES), so it works
// non-interactively from the service.
polkit.addRule(function (action, subject) {
    if (subject.user !== "lighthouse") {
        return polkit.Result.NOT_HANDLED;
    }
    if (action.id !== "org.freedesktop.systemd1.manage-units") {
        return polkit.Result.NOT_HANDLED;
    }
    var allowedVerbs = ["start", "stop", "restart"];
    var allowedUnits = [
$UNIT_ARRAY
    ];
    if (
        allowedVerbs.indexOf(action.lookup("verb")) !== -1 &&
        allowedUnits.indexOf(action.lookup("unit")) !== -1
    ) {
        return polkit.Result.YES;
    }
    return polkit.Result.NOT_HANDLED;
});
RULE
chmod 644 /etc/polkit-1/rules.d/50-lighthouse.rules
echo ">> polkit rule for units: $(echo "$UNIT_LIST" | tr '\n' ' ')"

# --- systemd unit -----------------------------------------------------------
install -m644 "$P/lighthouse.service" /etc/systemd/system/lighthouse.service
systemctl daemon-reload
systemctl enable lighthouse.service >/dev/null 2>&1 || true
echo ">> Provisioned. Ship code/assets with tugboat (deploy.toml)."
REMOTE

echo ">> Done."
